---
mock_rover:
  cmd_vel_topic: /mock_rover/cmd_vel
  odom_topic: /mock_rover/odom
  base_frame: base_link
  odom_frame: odom
  tick_rate_hz: 100.0

  gps:
    datum:
      lat: 45.0
      lon: -122.0
      heading_ned_degrees: 0.0
    publish_rate: 1.0
    topic: /gps/fix

  odometer:
    publish_rate: 10.0

  imu:
    publish_rate: 15.0
    topic: /imu/data
